apiVersion: v1
kind: Secret
metadata:
  name: user-service-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
stringData:
  DB_USER: hikuuser
  DB_PASS: hikupassword
  FLYWAY_URL: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
