{{- if .Values.azure.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "user-service.fullname" . }}-azure-kv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  {{- if .Values.gitops.enabled }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
  {{- end }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.kvCsiClientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: pg-host
          objectType: secret
        - |
          objectName: user-db-user
          objectType: secret
        - |
          objectName: user-db-password
          objectType: secret
        - |
          objectName: user-db-migrator-user
          objectType: secret
        - |
          objectName: user-db-migrator-password
          objectType: secret
        - |
          objectName: rabbitmq-default-user
          objectType: secret
        - |
          objectName: rabbitmq-default-pass
          objectType: secret
{{- end }}