CREATE SCHEMA IF NOT EXISTS user_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
