CREATE SCHEMA IF NOT EXISTS user_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA user_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;

    create table if not exists user_service.follows (
       id int8 generated by default as identity,
        createdAt timestamp not null,
        follower_id int8 not null,
        following_id int8 not null,
        primary key (id)
    );

    create table if not exists user_service.users (
       id int8 generated by default as identity,
        age int4,
        bio varchar(255),
        createdAt timestamp,
        email varchar(255) not null,
        fullName varchar(255),
        passwordHash varchar(255),
        profileImageUrl varchar(255),
        username varchar(255) not null,
        primary key (id)
    );

    alter table if exists user_service.follows 
       add constraint UK4faelgsm2rxl2jf3iyjy981ro unique (follower_id, following_id);

    alter table if exists user_service.users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists user_service.users 
       add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

    alter table if exists user_service.follows 
       add constraint FKqnkw0cwwh6572nyhvdjqlr163 
       foreign key (follower_id) 
       references user_service.users;

    alter table if exists user_service.follows 
       add constraint FKonkdkae2ngtx70jqhsh7ol6uq 
       foreign key (following_id) 
       references user_service.users;
