replicaCount: 1

environment: dev

image:
  repository: user-service
  tag: dev-latest
  pullPolicy: Never

database:
  enabled: true
  host: postgres.database.svc.cluster.local
  port: "5432"
  name: hikudb
  schema: user_service

azure:
  enabled: false

gitops:
  enabled: false

service:
  clusterIP:
    port: 8083
    address: "0.0.0.0"

  nodePort:
    enabled: true
    port: 8083
    nodePort: 30081

flyway:
  image:
    repository: user-service-migrator
    tag: "dev"
  url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
  user: hikuuser
  password: hikupassword
  baselineOnMigrate: true
  baselineVersion: 2

jwtAuth:
  issuer: "http://localhost:8080/auth/realms/hiku-dev"
  jwksUri: "http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/hiku-dev/protocol/openid-connect/certs"