replicaCount: 1

image:
  repository: user-service
  tag: dev-latest
  pullPolicy: Never

service:
  clusterIP:
    port: 8083

  nodePort:
    port: 8083
    nodePort: 30081

flyway:
  image:
    repository: user-service-migrator
    tag: "dev"
  url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
  user: hikuuser
  password: hikupassword
  baselineOnMigrate: true
  baselineVersion: 2